runtime: python39

handlers:
- url: /
  static_files: example-webstatic-app-engine/index.html
  upload: example-webstatic-app-engine/index.html

- url: /(.*)
  static_files: example-webstatic-app-engine/\1
  upload: example-webstatic-app-engine/(.*)